// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBslM1sj1ULv5trOEkzb2AQ3LHvmm2w19k',
    appId: '1:521822397146:web:ed525bb412042ac6027be3',
    messagingSenderId: '521822397146',
    projectId: 'flutter-aws-notifications',
    authDomain: 'flutter-aws-notifications.firebaseapp.com',
    storageBucket: 'flutter-aws-notifications.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwCZ3P_goMeJVv7Qsi6BQGIv4lglbbc_E',
    appId: '1:521822397146:android:af4c0142f4d8408b027be3',
    messagingSenderId: '521822397146',
    projectId: 'flutter-aws-notifications',
    storageBucket: 'flutter-aws-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFF87iT2SdTDn1QQdQYYnHhMwWY44hFUc',
    appId: '1:521822397146:ios:7a4b44ab6365fad0027be3',
    messagingSenderId: '521822397146',
    projectId: 'flutter-aws-notifications',
    storageBucket: 'flutter-aws-notifications.appspot.com',
    iosBundleId: 'br.com.andrey.quadros.aws.notifcation.flutterAwsNotification',
  );
}
